### PR TITLE
Fix issue #22

### LINKED ISSUE #22: Implement PUM and corresponding tests
The PUM (Preliminary Unlocking Matrix) feature and tests for it need to be implemented as according to the specification.

### PR DESCRIPTION
**Pull request by anass-coder**
Add PUMGenerator and it's tests

fixes #22

### CODE REVIEW

File: app/src/main/java/app/decide/PUMGenerator.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+        switch (op) {
+            case ANDD:
+                return i && j; 
+            case ORR:
+                return i || j; 
+            case NOTUSED:
+                return true;
+            default:
+                throw new IllegalArgumentException("Unknown connector type: " + op);
+        }
```
Comment (alixpeigue) [inline app/src/main/java/app/decide/PUMGenerator.java:53]: You can use a switch expression so you don't have to provide a default as the compiler checks for exhaustiveness

```java
return switch (op) {
    case ANDD -> i && j;
    case ORR -> i || j;
    case NOTUSED -> true;
};
```

**Comment by AdamFR00** [comment]
I do not see any issues either.

**Comment by alixpeigue** [comment]
Why are you merging without resolving conversations ?

**Comment by SetiQyu** [comment]
Sorry, overlooked that
