### PR TITLE
Fix: #42 Add error-handling and tests for FUV

### LINKED ISSUE #42: No error-handling for Fuv module
Currently there is no error-handling for Fuv.java which needs to be remedied.

### PR DESCRIPTION
**Pull request by SetiQyu**
This also should address #69 for FUV since the test cases formatting was updated. 
fixes #42

### CODE REVIEW

File: app/src/test/java/app/decide/FuvTest.java [hunk 1]
```diff
@@ -44,40 +51,64 @@ class FuvTest {
         }
 
     }
-    // If all elements in PUV and PUM are false then all FUV elements should be true 
+
+    /**
+     * Should throw an exception when any of the array lengths that 
+     * PUV or PUM consist of do not match the dimension parameter
+     */
+    @Test
```
Comment (alixpeigue) [inline app/src/test/java/app/decide/FuvTest.java:59]: We should chose whether we put @Test on the same line because it's not even coherent in the file.
I think putting them on the same line should be easier as there are more tests already formatted like that

Comment (SetiQyu) [reply app/src/test/java/app/decide/FuvTest.java]: Woops sorry, yeah one line seems reasonable since its used so often already
